### ISSUE TITLE
Change order of questions by Drag and Drop

### ISSUE THREAD

**Issue by sandrasie** [gossie/quiz#86]

**Comment by gossie** [comment]
Ich habe einen Branch angelegt, in dem das Backend implementiert ist. Einen Draft Pull Request habe ich auch angelegt (#116). Jede Frage hat jetzt das Property  `previousQuestionId`, in dem die Id der Frage darüber steht. Bei der ersten Frage steht null drinne. Wenn du jetzt eine Frage verschiebst, machst du den gleichen PUT Request, der auch beim Editieren von Fragen gemacht wird und schreibst in `previousQuestionId` die ID der Frage hinter der einsortiert werden soll. Wenn ganz nach oben geschoben werden soll, muss null drinne stehen. Der Rest, also das Verlinken der anderen betroffenen Fragen, passiert alles im Server.
**Wichtig:** Es müssen alle Information an der Frage stehen, so wie beim Editieren. Das Objekt im Server wird komplett ersetzt.
